# Generated by Django 5.2.5 on 2025-08-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_chatmessage_room_remove_chatmessage_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
