# Generated by Django 5.2.5 on 2025-08-19 18:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profiles/default.png', upload_to=accounts.models.profile_picture_upload_path),
        ),
    ]
