# Generated by Django 5.2.5 on 2025-08-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
    ]
