# Generated by Django 5.2.5 on 2025-08-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='game_thumbnails/', verbose_name='Thumbnail'),
        ),
    ]
