# Generated by Django 5.2.5 on 2025-08-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_game_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergamesession',
            name='game',
        ),
        migrations.RemoveField(
            model_name='usergamesession',
            name='user',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='UserGameSession',
        ),
    ]
