# Generated by Django 5.2.5 on 2025-08-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_usergamesession_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergamesession',
            name='game',
        ),
        migrations.AlterUniqueTogether(
            name='usergamesession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usergamesession',
            name='user',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='UserGameSession',
        ),
    ]
